language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37-test
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=lint

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox

notifications:
    slack: py-libp2p:RK0WVoQZhQXLgIKfHNPL1TR2
