language: python

python:
  - "3.6"

install:
  - pip install codecov pytest pytest-cov
  - python setup.py develop

script:
  - py.test --cov=./libp2p tests/
  - pylint --rcfile=.pylintrc libp2p tests

after_success:
  - codecov

notifications:
    slack: py-libp2p:RK0WVoQZhQXLgIKfHNPL1TR2

