language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      after_success:
        - codecov
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=lint

install:
  - pip install --upgrade pip codecov

script:
  - tox

notifications:
    slack: py-libp2p:RK0WVoQZhQXLgIKfHNPL1TR2
